In [ ]:
import numpy as np

stu_marks = np.array([
    [10, 20, 30],
    [11, 12, 12],
    [14, 16, 19],
])

max = np.max(stu_marks)
min = np.min(stu_marks)
avg = np.average(stu_marks)

print("Maximum: ", max)
print("Minimum: ", min)
print("Average: ",avg)

print("Slicing the marks of the student 1: ", stu_marks[1])

print("\n")
print("Indexes of the students scoring High marks")
high = np.any(stu_marks > 12, axis=1)
for h in range(len(high)):
  if high[h] == True:
    print(h)

print("\nReshaped Array (Subject-wise):\n", stu_marks.T)

Maximum:  30
Minimum:  10
Average:  16.0
Slicing the marks of the student 1:  [11 12 12]


Indexes of the students scoring High marks
0
2

Reshaped Array (Subject-wise):
 [[10 11 14]
 [20 12 16]
 [30 12 19]]
