In [3]:
import numpy as np

mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

add = np.add(mat1, mat2)
sub = np.subtract(mat1, mat2)

print("Addition: \n", add)
print("Subtraction: \n", sub)

Addition: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction: 
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [4]:
import numpy as np

mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

dot = np.dot(mat1, mat2)

print("Dot Product: \n", dot)

Dot Product: 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
